# Generated by Django 5.1.7 on 2025-04-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('data', models.DateField(blank=True, default=datetime.date(2025, 4, 5), null=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='../static/img/', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'unique_together': {('name', 'data', 'image')},
            },
        ),
    ]
