# Generated by Django 5.1.7 on 2025-04-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0003_alter_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(upload_to='media/pictures/', verbose_name='Картинка'),
        ),
    ]
