# Generated by Django 5.1.7 on 2025-04-09 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0008_alter_picture_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='data',
            field=models.DateField(blank=True, default=datetime.date(2025, 4, 9), null=True, verbose_name='Дата'),
        ),
    ]
