# Generated by Django 5.1.7 on 2025-04-09 16:53

from django.db import migrations

def set_picture_user(apps, schema_editor):
    Picture = apps.get_model('picture', 'Picture')
    User = apps.get_model('auth', 'User')
    default_user, _ = User.objects.get_or_create(
        username='picture_default_user',
        defaults={'password': 'unusable_password'}
    )
    Picture.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('picture', '0010_picture_user'),
    ]
    operations = [migrations.RunPython(set_picture_user)]

