# Generated by Django 5.1.7 on 2025-04-07 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='description',
        ),
        migrations.RemoveField(
            model_name='music',
            name='duration',
        ),
    ]
