# Generated by Django 5.1.7 on 2025-04-09 16:12


from django.db import migrations

def fill_user(apps, schema_editor):
    Book = apps.get_model('books', 'Book')  # Получаем модель Book
    User = apps.get_model('auth', 'User')  # Получаем модель User
    
    # Находим первого пользователя (или любого другого, например, суперпользователя)
    default_user = User.objects.filter(is_superuser=True).first()  
    
    # Если пользователей нет — создаём (опционально)
    if not default_user:
        default_user = User.objects.create_user(
            username='default_user',
            password='temp_password'
        )
    
    # Привязываем все книги к этому пользователю
    Book.objects.all().update(user=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('books', '0003_book_user'),  # Укажите имя последней миграции
    ]
    
    operations = [
        migrations.RunPython(fill_user),  # Запускаем функцию заполнения
    ]

