# Generated by Django 5.1.7 on 2025-04-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='pictures/', verbose_name='Фото')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, help_text='В формате +375XXXXXXXXX или 80XXXXXXXXX', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, help_text='Введите действительный email адрес', max_length=255, null=True, unique=True, verbose_name='Электронная почта')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('hobby', models.TextField(blank=True, null=True, verbose_name='Хобби')),
            ],
        ),
    ]
