# Generated by Django 5.1.7 on 2025-04-09 16:21

from django.db import migrations


def set_default_user(apps, schema_editor):
    PersonalData = apps.get_model('main', 'PersonalData')
    User = apps.get_model('auth', 'User')
    
    # Находим или создаём пользователя для старых записей
    default_user, _ = User.objects.get_or_create(
        username='default_user',
        defaults={'password': 'unusable_password'}
    )
    
    # Обновляем все записи без пользователя
    PersonalData.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_personaldata_user'),  # Например: '0002_auto_20230101'
    ]
    
    operations = [
        migrations.RunPython(set_default_user),
    ]


