# Generated by Django 5.1.6 on 2025-02-06 17:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-time'], 'verbose_name': ['Распорядок дня'], 'verbose_name_plural': ['Распорядок дня']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': ['Меню'], 'verbose_name_plural': ['Меню']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-data'], 'verbose_name': ['Запись'], 'verbose_name_plural': ['Записи']},
        ),
        migrations.AddField(
            model_name='day',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.record'),
        ),
        migrations.AddField(
            model_name='menu',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.record'),
        ),
        migrations.AddField(
            model_name='record',
            name='weekday',
            field=models.CharField(default='mn', max_length=2),
        ),
        migrations.AlterField(
            model_name='day',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='comment_menu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dinner',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='snack',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 2, 6)),
        ),
    ]
