# Generated by Django 5.1.6 on 2025-02-12 12:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_day_activity_alter_day_comment_alter_day_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-time'], 'verbose_name': 'Распорядок дня', 'verbose_name_plural': 'Распорядок дня'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-data'], 'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterField(
            model_name='day',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='record.record'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='record.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 2, 12), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weekday',
            field=models.CharField(choices=[('пн', 'понедельник'), ('вт', 'вторник'), ('ср', 'среда'), ('чт', 'четверг'), ('пт', 'пятница'), ('сб', 'суббота'), ('вс', 'воскресенье')], db_default=0, default='пн', max_length=2, verbose_name='День недели'),
        ),
    ]
