# Generated by Django 5.1.6 on 2025-02-17 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_day_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['time'], 'verbose_name': 'Распорядок дня', 'verbose_name_plural': 'Распорядок дня'},
        ),
        migrations.AlterField(
            model_name='day',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Завтрак'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='comment_menu',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dinner',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Обед'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='snack',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Перекус'),
        ),
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 2, 17), verbose_name='Дата'),
        ),
    ]
