# Generated by Django 5.1.6 on 2025-02-21 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_day_options_alter_day_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 2, 21), verbose_name='Дата'),
        ),
    ]
