# Generated by Django 5.1.6 on 2025-03-30 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_record_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 3, 30), verbose_name='Дата'),
        ),
    ]
