# Generated by Django 5.1.7 on 2025-04-04 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_alter_record_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 4, 4), verbose_name='Дата'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('time', 'record')},
        ),
    ]
