# Generated by Django 5.1.7 on 2025-04-04 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_alter_record_data_alter_day_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='record.record', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='record.record', verbose_name='Запись'),
        ),
    ]
