# Generated by Django 5.1.7 on 2025-04-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_alter_day_record_alter_menu_record'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('record',), name='unique_menu_per_record', violation_error_message='Меню уже существует для этой записи'),
        ),
    ]
