# Generated by Django 5.1.7 on 2025-04-05 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_menu_unique_menu_per_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 4, 5), verbose_name='Дата'),
        ),
    ]
