# Generated by Django 5.1.7 on 2025-04-06 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_alter_record_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data',
            field=models.DateField(default=datetime.date(2025, 4, 6), verbose_name='Дата'),
        ),
    ]
