# Generated by Django 5.1.7 on 2025-04-09 17:05

from django.db import migrations
from django.contrib.auth.models import User

def create_default_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    user, created = User.objects.get_or_create(
        username='migration_temp_user',
        defaults={
            'password': 'unusable_password',
            'is_active': False,
            'is_superuser': False
        }
    )
    return user

def populate_users(apps, schema_editor):
    Record = apps.get_model('record', 'Record')
    Day = apps.get_model('record', 'Day')
    Menu = apps.get_model('record', 'Menu')
    
    default_user = create_default_user(apps, schema_editor)

    Record.objects.filter(user__isnull=True).update(user=default_user)
    Day.objects.filter(user__isnull=True).update(user=default_user)
    Menu.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):
    dependencies = [
        ('record', '0017_day_user_menu_user_record_user'), 
    ]
    
    operations = [
        migrations.RunPython(populate_users),
    ]

